<?php
$rota_css = WEBFILES.'src/views/web-files/css/';
$rota_js = WEBFILES.'src/views/web-files/js/';
$rota_paginas = WEBFILES;
?>
<!DOCTYPE html>
<html>
<head>
	<title>Página Não Encontrada</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $rota_css; ?>bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $rota_css; ?>layout.css" />
</head>
<body>
	<br /><br /><br />
	<h1><center>Página Não Encontrada</center></h1>
	
	<script src="<?php echo $rota_js; ?>jquery.js" type="text/javascript" charset="utf-8"></script>
	<script src="<?php echo $rota_js; ?>bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="<?php echo $rota_js; ?>script.js" type="text/javascript" charset="utf-8"></script>
</body>
</html>